### ISSUE TITLE
Error when calling listeners_all()

### ISSUE THREAD

**Issue by benjavides** [riga/pymitter#4]
Hi, I'm getting the following error whenever I call .listener_all("eventName")

`File "C:\...\Lib\pymitter.py", line 207, in listeners_all
    branches.extend(b.values())
AttributeError: 'dict_values' object has no attribute 'extend'
Results of run operation resulted in exception.`

It may be my python version (3.7.2).

I fixed it by changing line 201 in pymitter.py
from: 
`branches = self._tree.values()`
to:
`branches = list(self._tree.values())`

**Comment by riga** [comment]
Thanks for reporting @benjavides ,
I will add full Python 3 support soon.

**Comment by riga** [comment]
Fixed in e43fa72.
