### ISSUE TITLE
Custom `on` function with decorator.

### ISSUE THREAD

**Issue by ghost** [riga/pymitter#5]
Hi! How can I create a custom `on` function with class decorator? This is an example:
```python
class Bot:
    def __init__(self):
        self.ee = EventEmitter()
    
    def connect(self):
        self.ee.emit('connected', {'op': 3})
```
And how i want it to be:
```python
from .mypackage import Bot
bot = Bot()

@bot.on('connected')
async def on_connected(data):
 print(data)
```
Thanks for any help.

**Comment by riga** [comment]
_Deleted my previous answer_ 

You can either ad a method `on()` to your `Bot` class and forward it to `ee`,

```python
class Bot:
    ...
    def on(*args, **kwargs):
        return self.ee.on(*args, **kwargs)
````

or you use `@bot.ee.on(...)` to decorate a callback.

Hope that helps.
