### ISSUE TITLE
Support async functions

### ISSUE THREAD

**Issue by jchristi** [riga/pymitter#6]
When I register a callback function that is an async function, I see this runtime warning:
```
/venv/lib64/python3.10/site-packages/pymitter.py:273: RuntimeWarning: coroutine '<my function>' was never awaited
  self.func(*args, **kwargs)
```

**Comment by riga** [comment]
Full coroutine support is added since [v0.4.0](https://github.com/riga/pymitter/releases/tag/v0.4.0).
