### ISSUE TITLE
Question: Do the decorators support instantiated classes?

### ISSUE THREAD

**Issue by wes8ty** [riga/pymitter#8]
I am trying to add a decorator to a method in an instantiated class but I keep getting the following error. Is this supposed to support instantiated classes? I don't see any examples doing it this way.
```
class BluetoothMngr():

    def __init__(self):
        pass
    
    @ee.on(EventHeartBeat.CHANGE_HEARTBEAT, True)
    def enable_heartbeat_led(self) -> None:
        """
        Enabled the blinking of the heartbeat LED
        """
        pass
```
```
missing 1 required positional argument: 'self'
```

If I register it in the `__init__` of the class, it works fine:
```
ee.on(EventBtn.CHANGE_HEARTBEAT, self.enable_heartbeat_led)
```

Example Code:
```
# --------------------------------------------------
# Module Variables
# --------------------------------------------------
ee = EventEmitter()
```

**Comment by riga** [comment]
@wes8ty Thanks for opening the issue! 
I'm looking into this.

**Comment by riga** [comment]
I finally had the time to dive into this again, and I believe you should go with

```python
ee.on(EventBtn.CHANGE_HEARTBEAT, self.enable_heartbeat_led)
```

i.e., registering things in your init. The event emitter object is usually created outside and doesn't know anything about your class and - more importantly - its instances. When registering callbacks in your init, this issue is avoided as you actively declare methods of an already created instance (`self`) as a callback.

On a different note, I think you shouldn't pass  `True` in `@ee.on(EventHeartBeat.CHANGE_HEARTBEAT, True)` as this disqualifies the decorator usage, which expects the function to be decorated as the second argument.

Hope this helps!

**Comment by wes8ty** [comment]
Hi @riga!

Thank you for looking into my question. In regards to not passing `True`, you are absolutely right. I only should pass args on the `emit` methods.

It would be awesome to be able to use the decorator for an instantiated class. I like to see which methods are called externally (using events) rather than methods that are part of the class itself. Is there a solution to supporting that or is that outside of the scope of the library?

**Comment by riga** [comment]
I think this feature would be too specific to be part of the library itself, but something as simple as

```python
ee = EventEmitter()

class BluetoothMngr(object):

    def __init__(self):
        super().__init__()

        # add all callable functions as callbacks
        # (there are tons of cleaner ways to identify them ;) )
        for func in self.__dict__.values():
            if not callable(func):
                continue
            event = f"BluetoothMngr.event.{func.__name__}"
            ee.on(event, func)

    # instance methods go here
    ...
```

could do the trick (if I understood your use case correctly), no?

**Comment by riga** [comment]
Closing this one for now.

**Comment by wes8ty** [comment]
Sorry about the delay. I do like how clean decorators are to identify methods within a class upfront if they are tied to events than registering them in the __init__ dunder method. I guess I will have to use some naming convention to identify those methods that should not be called directly. Thanks for the quick answers to my questions!
