### ISSUE TITLE
[Feature] Suggested improvement for wildcard use.

### ISSUE THREAD

**Issue by danboyle7** [riga/pymitter#9]
Hello!

It would be useful if you could trigger all subsequent namespace events, with a single wildcard, i.e.

If you have 

```
em = EventEmitter()

@em.on("event.*")
def on_event():
    print("Triggering event")
```

it will not be triggered by an emit call like:
```
em.emit("event.foo.bar.xxx")
```

but there could be a usefulness to calling all child namespace events in the way I mentioned above.

This could be easily be done by adding the following: 
```
# first make sure that pattern matches _this_ name
if not self.check_name(pattern):
    return []

# --> ADDING THESE LINE (inside of find_nodes)
if self.wildcard and self.name == "*" and not self.nodes:
    return [self]

# when there are no sub patterns, return this one
if not sub_patterns:
    return [self]
```

or you merge it with the condition below if you pleased, that may be a personal preference tho. If this is not a desired outcome, then that is fine, just thought I would add my two cents.

Thanks,
Daniel

**Comment by riga** [comment]
Hi @danboyle7 ,

thanks for opening this feature request!

In fact, I thought about this extension of the wildcard support in the past, but using a single `*` to match namespaces at any level might be a bit misleading(1) and it would introduce a breaking change at this point.

I even added tests that explicitly check that handlers at deeper levels are *not* triggered:

https://github.com/riga/pymitter/blob/51fb1ac7dc1e43a133cb1bd7bf1bd960f1d3010d/tests.py#L140-L141

(1) For better control over which namespaces are considered and which events are triggered, I think a mechanism similar to the one used for matching paths in `.gitignore` files ([example](https://stackoverflow.com/questions/16550688/how-to-gitignore-files-recursively)), i.e., explicitly using `**`, would be needed.

For instance,

```python
@em.on("foo.bar.test")
def handler():
    pass

em.emit("**.test")
```

would be intuitive to anyone who worked with `.gitignore` files before. However, this requires a few more changes to the tree search that is currently in place. I'm not sure yet if there is a showstopper, but I will look into this further in the next week.

**Comment by riga** [comment]
I checked again what needs to be done implementation-wise and think that the entire matching  mechanism would essentially need a rewrite to understand `**` at potentially multiple depths in both handler and trigger event strings.

At this point, I don't think that it's worth it, but if there are more requests in this direction I would reconsider looking into this.
